# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 936eeba0cc7f294d171a6bc74790da2eea3fdd1292b7b6520dcc2d46c2dcccd4a022c4faa6b300162f07324dbd7b2090a3d3a72d78e1802b5969e930cd6971a8

test:
  secret_key_base: 99ae51079fc89817ad3de787a08b22628a5c821468d855410109ee513b98e5e3ed65ad5bd0441caf90bc753d9da2b0acedb9355bc1030def1b48196b18597274

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
